version: '3'
services:
    # rabbitmq:
    #     image: rabbitmq:3.8.3-management
    #     container_name: yun-rabbitmq
    #     restart: always
    #     hostname: myRabbitmq
    #     ports:
    #       - 15672:15672
    #       - 5672:5672
    #     volumes:
    #       - ./rabbitmq/data:/var/lib/rabbitmq
    #     environment:
    #       - RABBITMQ_DEFAULT_USER=root
    #       - RABBITMQ_DEFAULT_PASS=root
    mysql:
        image: mysql:8.0.21
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/conf:/etc/mysql
            - ./mysql/mysql-files:/var/lib/mysql-files/
        ports:
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=123456
        container_name: yun-mysql
    redis:
        image: redis:alpine
        ports:
            - 6397:6379
        volumes: 
            - ./redis/data:/data
        container_name: yun-redis
    nginx:
        image: nginx:latest
        ports:
            - 80:80
        depends_on:
            - php
        volumes:
            - ./nginx/conf/conf.d:/etc/nginx/conf.d
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - /Users/mac/Codes/php:/usr/share/nginx/html:cached
        container_name: yun-nginx
        environment: 
            - TZ=Asia/Shanghai
    php:
        build: ./php
        ports:
            - 9000:9000
        volumes:
            - /Users/mac/Codes/php:/var/www/html:cached
            - ./php/conf:/usr/local/etc/php
        container_name: yun-php
        environment: 
            - TZ=Asia/Shanghai
